ARDMK_DIR			   = /usr/share/arduino
BOARD_TAG 			   = uno
ARDUINO_DIR            = /usr/share/arduino
TARGET                 = blinky
ARDUINO_LIBS           =
MCU                    = atmega328p
F_CPU                  = 16000000
ARDUINO_PORT           = /dev/ttyACM0
AVRDUDE_ARD_BAUDRATE   = 115200
AVRDUDE_ARD_PROGRAMMER = arduino
MONITOR_BAUDRATE 	   = 115200
include $(ARDMK_DIR)/Arduino.mk